(** Encoding from CCS nets into CCS processes.

    This module implements Algorithm 1 of:

      Hernán C. Melgratti, Claudio Antares Mezzina, G. Michele Pinna.
      "Encoding Reversible Petri nets into CCSK."

    Given a {b CCS net} (a [Net.labelled_net] in which every transition has
    at most two places in its preset, and exactly two only when its label is
    [tau]) together with a marking, the algorithm produces:

    - a {i partial mapping of defining equations} [D], associating to every
      place [s] of the net a process variable [Xs] whose defining equation
      describes the possible evolutions of [s] (Step 1-3 of the algorithm);
      synchronising transitions additionally introduce a fresh restricted
      action (Step 5-8);
    - a CCS process [Q], namely the parallel composition of (as many copies
      as the marking prescribes of) the place variables, restricted on the
      fresh synchronisation actions (Step 10-11).

    Theorem 1 of the paper states that the marking graph of the CCS net
    system is bisimilar to the LTS generated by [Q] under [D]. *)

open Net
open Ccsk.CCS

(** The process variable [Xs] associated to a place [s]. *)
let var_of_place (pid : place_id) : string = "X" ^ pid

(** The auxiliary variable [Yt] associated to a transition [t], used while
    the equation of a place is being built (Step 2) before being substituted
    away (Steps 3 and 7-8). *)
let var_of_trans (tid : transition_id) : string = "Y" ^ tid

(** The fresh restricted action [st] associated to a synchronising
    transition [t] (Step 5-8 of Algorithm 1). *)
let action_of_sync (tid : transition_id) : string = "s" ^ tid

(* Labels                                                              *)

(** Look up the action [lambda(t)] labelling a transition, as recorded in
    [net.label]. We follow the convention used throughout the test-suite:
    the label ["tau"] (or the empty label) denotes the silent action, any
    other string [a] denotes the input action [a], and a label of the form
    ["!a"] denotes the output (co-)action [a]. *)
let label_of_transition (net : labelled_net) (tid : transition_id) : string =
  match List.find_opt (fun t -> t.t_id = tid) net.label with
  | Some t -> t.t_label
  | None ->
      (match List.find_opt (fun t -> t.t_id = tid) net.transitions with
       | Some t -> t.t_label
       | None -> failwith ("label_of_transition: unknown transition " ^ tid))

let act_of_label (lbl : string) : Ccsk.act =
  if lbl = "tau" || lbl = "" then Ccsk.Silent
  else if String.length lbl > 0 && lbl.[0] = '!' then
    Ccsk.Output (String.sub lbl 1 (String.length lbl - 1))
  else Ccsk.Input lbl

(* ------------------------------------------------------------------ *)
(* Step 1-3: defining equations for places, substituting the equation  *)
(* of each non-synchronising transition into the defining equation of  *)
(* its (unique) input place.                                           *)
(* ------------------------------------------------------------------ *)

(** [is_sync net t] holds when [|•t| = 2], i.e. [t] is a synchronising
    transition in the sense of [Net.Definition 7] (CCS nets). *)
let is_sync (net : labelled_net) (tid : transition_id) : bool =
  List.length (preset_of_transition net tid) = 2

(** [choice_of_list ps] builds the (possibly empty) choice [Y1 + .. + Yk]
    out of a non-empty list of processes; the empty list yields [Zero],
    matching the case of a place with no outgoing transitions. *)
let choice_of_list (ps : process list) : process =
  match ps with
  | [] -> Zero
  | p :: ps -> List.fold_left (fun acc p -> Choice (acc, p)) p ps

(** [parallel_of_list ps] builds [X1 | .. | Xn] out of a (possibly empty)
    list of processes; the empty list yields [Zero] (the postset of a
    transition is empty exactly when it produces no tokens, which does
    not occur for transitions of a CCS net but is handled defensively). *)
let parallel_of_list (ps : process list) : process =
  match ps with
  | [] -> Zero
  | p :: ps -> List.fold_left (fun acc p -> Parallel (acc, p)) p ps

(** Step 2: initialise [D(Xs) = Yt1 + .. + Ytk] for every place [s], where
    [t1,..,tk] are the transitions in the postset of [s]. *)
let init_place_equations (net : labelled_net) : equations =
  List.map
    (fun s ->
      let outgoing = postset_of_place net s.p_id in
      let rhs =
        choice_of_list (List.map (fun t -> Var (var_of_trans t.t_id)) outgoing)
      in
      (var_of_place s.p_id, rhs))
    net.places

(** Substitute every occurrence of variable [x] by [repl] in the right-hand
    side of every equation of [d] (used to eliminate the auxiliary [Yt]
    variables once their definition has been computed). *)
let subst_in_equations (x : string) (repl : process) (d : equations) :
    equations =
  List.map (fun (y, p) -> (y, subst x repl p)) d

(** Step 3: for every non-synchronising transition [t] (single place [s_star]
    in its preset), substitute [Yt] in [D(Xs_star)] by [lambda(t).(Xs1 | .. |
    Xsn)] where [s1,..,sn] is the postset of [t]. *)
let encode_simple_transitions (net : labelled_net) (d : equations) : equations
    =
  List.fold_left
    (fun d t ->
      if is_sync net t.t_id then d
      else
        let preset = preset_of_transition net t.t_id in
        match preset with
        | [ _s_star ] ->
            let cont =
              parallel_of_list
                (List.map
                   (fun s -> Var (var_of_place s.p_id))
                   (postset_of_transition net t.t_id))
            in
            let rhs = Prefix (act_of_label (label_of_transition net t.t_id), cont) in
            subst_in_equations (var_of_trans t.t_id) rhs d
        | [] ->
            (* A transition with empty preset never fires under the token
               game of Definition 5/6: there is nothing to substitute. *)
            d
        | _ ->
            failwith
              ("encode_simple_transitions: transition " ^ t.t_id
             ^ " is not a CCS-net transition (|.t| > 1 but label <> tau)"))
    d net.transitions

(* ------------------------------------------------------------------ *)
(* Step 4-9: synchronising transitions (|•t| = 2, labelled tau).       *)
(* ------------------------------------------------------------------ *)

(** [subst_var_in_one_equation x repl x_eq d] substitutes [x] by [repl] only
    in the right-hand side of the equation for variable [x_eq], leaving
    every other equation untouched. Used by {!encode_sync_transitions},
    where the same auxiliary variable [Yt] must be resolved differently
    depending on which of the two equations (preset places) mentions it:
    the place that "opens" the synchronisation gets the continuation, the
    place that "closes" it gets [at.0]. *)
let subst_var_in_one_equation (x : string) (repl : process) (x_eq : string)
    (d : equations) : equations =
  List.map (fun (y, p) -> if y = x_eq then (y, subst x repl p) else (y, p)) d

(** Step 5-8: for every synchronising transition [t] with preset
    [{s1, s2}], pick a fresh action [at]. The equation [D(Xs1)] (which
    mentions [Yt] as one of its summands) is updated by substituting [Yt]
    with [at.(Xs1' | .. | Xsn')] -- the continuation, where [s1',..,sn'] is
    the postset of [t] -- while [D(Xs2)] is updated by substituting [Yt]
    with [at.0]. Returns the updated equations together with the set of
    fresh actions introduced. *)
let encode_sync_transitions (net : labelled_net) (d : equations) :
    equations * string list =
  List.fold_left
    (fun (d, fresh_actions) t ->
      if not (is_sync net t.t_id) then (d, fresh_actions)
      else
        match preset_of_transition net t.t_id with
        | [ s1; s2 ] ->
            let at = action_of_sync t.t_id in
            let cont =
              parallel_of_list
                (List.map
                   (fun s -> Var (var_of_place s.p_id))
                   (postset_of_transition net t.t_id))
            in
            let rhs_open = Prefix (Input at, cont) in
            let rhs_close = Prefix (Output at, Zero) in
            let yt = var_of_trans t.t_id in
            let d =
              d
              |> subst_var_in_one_equation yt rhs_open (var_of_place s1.p_id)
              |> subst_var_in_one_equation yt rhs_close (var_of_place s2.p_id)
            in
            (d, at :: fresh_actions)
        | _ ->
            failwith
              ("encode_sync_transitions: synchronising transition "
             ^ t.t_id ^ " does not have exactly two places in its preset"))
    (d, []) net.transitions

(* The two substitutions above are now confined, by construction, to a
   single equation each ([s1]'s and [s2]'s respectively) via
   {!subst_var_in_one_equation}, so the order in which they are applied
   does not matter and [Yt] is correctly resolved differently on each
   side of the synchronisation, as prescribed by Steps 7-8 of the
   algorithm. *)

(* ------------------------------------------------------------------ *)
(* Step 10-11: assembling the final process.                          *)
(* ------------------------------------------------------------------ *)

(** [replicate n p] builds the parallel composition of [n] copies of [p]
    ([X^n] in the notation of the paper); [replicate 0 p = Zero]. *)
let replicate (n : int) (p : process) : process =
  if n <= 0 then Zero
  else
    let rec go k = if k = 1 then p else Parallel (p, go (k - 1)) in
    go n

(** Step 11: [Q = X_{s1}^{m(s1)} | .. | X_{sn}^{m(sn)}], skipping unmarked
    places (whose contribution is [Zero] and would otherwise clutter the
    process with inert summands). *)
let assemble_marking (net : labelled_net) (m : marked_net) : process =
  let contributions =
    List.filter_map
      (fun s ->
        let n = tokens m s.p_id in
        if n <= 0 then None
        else Some (replicate n (Var (var_of_place s.p_id))))
      net.places
  in
  parallel_of_list contributions

(** Step 11: restrict [Q] on every fresh synchronisation action. *)
let restrict_all (actions : string list) (q : process) : process =
  match actions with [] -> q | actions -> Restriction (q, actions)

(* ------------------------------------------------------------------ *)
(* Algorithm 1.                                                       *)
(* ------------------------------------------------------------------ *)

type result = { process : process; equations : equations }

(** [encode (net, m)] runs Algorithm 1 on the CCS net [net] with marking
    [m], producing the CCS process [Q] and the (now [Yt]-free) defining
    equations [D] such that, by Theorem 1, the marking graph of [(net, m)]
    is bisimilar to the LTS generated by [Q] under [D]. *)
let encode (m : marked_net) : result =
  let net = m.net in
  let d0 = init_place_equations net in
  let d1 = encode_simple_transitions net d0 in
  let d2, fresh_actions = encode_sync_transitions net d1 in
  let q = assemble_marking net m |> restrict_all fresh_actions in
  { process = q; equations = d2 }

(* ------------------------------------------------------------------ *)
(* Pretty-printing                                                    *)
(* ------------------------------------------------------------------ *)

let string_of_equations (d : equations) : string =
  d
  |> List.map (fun (x, p) -> x ^ " = " ^ string_of_process p)
  |> String.concat "\n"

let print_result (r : result) : unit =
  Printf.printf "Q = %s\n\nD:\n%s\n" (string_of_process r.process)
    (string_of_equations r.equations)
